/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DespreNoiRouteImport } from './routes/despre-noi'
import { Route as PacheteFunerareIndexRouteImport } from './routes/pachete-funerare.index'
import { Route as PacheteFunerareSlugRouteImport } from './routes/pachete-funerare.$slug'
import { Route as ProduseFunerareIndexRouteImport } from './routes/produse-funerare.index'
import { Route as ServiciiIndexRouteImport } from './routes/servicii.index'
import { Route as ServiciiSlugRouteImport } from './routes/servicii.$slug'
import { Route as ProduseFunerareCategorieIndexRouteImport } from './routes/produse-funerare.$categorie.index'
import { Route as ProduseFunerareCategorieSlugRouteImport } from './routes/produse-funerare.$categorie.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreNoiRoute = DespreNoiRouteImport.update({
  id: '/despre-noi',
  path: '/despre-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const PacheteFunerareIndexRoute = PacheteFunerareIndexRouteImport.update({
  id: '/pachete-funerare/',
  path: '/pachete-funerare/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacheteFunerareSlugRoute = PacheteFunerareSlugRouteImport.update({
  id: '/pachete-funerare/$slug',
  path: '/pachete-funerare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduseFunerareIndexRoute = ProduseFunerareIndexRouteImport.update({
  id: '/produse-funerare/',
  path: '/produse-funerare/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiIndexRoute = ServiciiIndexRouteImport.update({
  id: '/servicii/',
  path: '/servicii/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiSlugRoute = ServiciiSlugRouteImport.update({
  id: '/servicii/$slug',
  path: '/servicii/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduseFunerareCategorieIndexRoute =
  ProduseFunerareCategorieIndexRouteImport.update({
    id: '/produse-funerare/$categorie/',
    path: '/produse-funerare/$categorie/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProduseFunerareCategorieSlugRoute =
  ProduseFunerareCategorieSlugRouteImport.update({
    id: '/produse-funerare/$categorie/$slug',
    path: '/produse-funerare/$categorie/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/pachete-funerare/$slug': typeof PacheteFunerareSlugRoute
  '/servicii/$slug': typeof ServiciiSlugRoute
  '/pachete-funerare/': typeof PacheteFunerareIndexRoute
  '/produse-funerare/': typeof ProduseFunerareIndexRoute
  '/servicii/': typeof ServiciiIndexRoute
  '/produse-funerare/$categorie/$slug': typeof ProduseFunerareCategorieSlugRoute
  '/produse-funerare/$categorie/': typeof ProduseFunerareCategorieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/pachete-funerare/$slug': typeof PacheteFunerareSlugRoute
  '/servicii/$slug': typeof ServiciiSlugRoute
  '/pachete-funerare': typeof PacheteFunerareIndexRoute
  '/produse-funerare': typeof ProduseFunerareIndexRoute
  '/servicii': typeof ServiciiIndexRoute
  '/produse-funerare/$categorie/$slug': typeof ProduseFunerareCategorieSlugRoute
  '/produse-funerare/$categorie': typeof ProduseFunerareCategorieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/pachete-funerare/$slug': typeof PacheteFunerareSlugRoute
  '/servicii/$slug': typeof ServiciiSlugRoute
  '/pachete-funerare/': typeof PacheteFunerareIndexRoute
  '/produse-funerare/': typeof ProduseFunerareIndexRoute
  '/servicii/': typeof ServiciiIndexRoute
  '/produse-funerare/$categorie/$slug': typeof ProduseFunerareCategorieSlugRoute
  '/produse-funerare/$categorie/': typeof ProduseFunerareCategorieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/despre-noi'
    | '/pachete-funerare/$slug'
    | '/servicii/$slug'
    | '/pachete-funerare/'
    | '/produse-funerare/'
    | '/servicii/'
    | '/produse-funerare/$categorie/$slug'
    | '/produse-funerare/$categorie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/despre-noi'
    | '/pachete-funerare/$slug'
    | '/servicii/$slug'
    | '/pachete-funerare'
    | '/produse-funerare'
    | '/servicii'
    | '/produse-funerare/$categorie/$slug'
    | '/produse-funerare/$categorie'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/despre-noi'
    | '/pachete-funerare/$slug'
    | '/servicii/$slug'
    | '/pachete-funerare/'
    | '/produse-funerare/'
    | '/servicii/'
    | '/produse-funerare/$categorie/$slug'
    | '/produse-funerare/$categorie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DespreNoiRoute: typeof DespreNoiRoute
  PacheteFunerareSlugRoute: typeof PacheteFunerareSlugRoute
  ServiciiSlugRoute: typeof ServiciiSlugRoute
  PacheteFunerareIndexRoute: typeof PacheteFunerareIndexRoute
  ProduseFunerareIndexRoute: typeof ProduseFunerareIndexRoute
  ServiciiIndexRoute: typeof ServiciiIndexRoute
  ProduseFunerareCategorieSlugRoute: typeof ProduseFunerareCategorieSlugRoute
  ProduseFunerareCategorieIndexRoute: typeof ProduseFunerareCategorieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-noi': {
      id: '/despre-noi'
      path: '/despre-noi'
      fullPath: '/despre-noi'
      preLoaderRoute: typeof DespreNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pachete-funerare/': {
      id: '/pachete-funerare/'
      path: '/pachete-funerare'
      fullPath: '/pachete-funerare/'
      preLoaderRoute: typeof PacheteFunerareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pachete-funerare/$slug': {
      id: '/pachete-funerare/$slug'
      path: '/pachete-funerare/$slug'
      fullPath: '/pachete-funerare/$slug'
      preLoaderRoute: typeof PacheteFunerareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produse-funerare/': {
      id: '/produse-funerare/'
      path: '/produse-funerare'
      fullPath: '/produse-funerare/'
      preLoaderRoute: typeof ProduseFunerareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii/': {
      id: '/servicii/'
      path: '/servicii'
      fullPath: '/servicii/'
      preLoaderRoute: typeof ServiciiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii/$slug': {
      id: '/servicii/$slug'
      path: '/servicii/$slug'
      fullPath: '/servicii/$slug'
      preLoaderRoute: typeof ServiciiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produse-funerare/$categorie/': {
      id: '/produse-funerare/$categorie/'
      path: '/produse-funerare/$categorie'
      fullPath: '/produse-funerare/$categorie/'
      preLoaderRoute: typeof ProduseFunerareCategorieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produse-funerare/$categorie/$slug': {
      id: '/produse-funerare/$categorie/$slug'
      path: '/produse-funerare/$categorie/$slug'
      fullPath: '/produse-funerare/$categorie/$slug'
      preLoaderRoute: typeof ProduseFunerareCategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DespreNoiRoute: DespreNoiRoute,
  PacheteFunerareSlugRoute: PacheteFunerareSlugRoute,
  ServiciiSlugRoute: ServiciiSlugRoute,
  PacheteFunerareIndexRoute: PacheteFunerareIndexRoute,
  ProduseFunerareIndexRoute: ProduseFunerareIndexRoute,
  ServiciiIndexRoute: ServiciiIndexRoute,
  ProduseFunerareCategorieSlugRoute: ProduseFunerareCategorieSlugRoute,
  ProduseFunerareCategorieIndexRoute: ProduseFunerareCategorieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
